### ISSUE TITLE
[PE-D][Tester D] Program only saves upon exit command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-F10-3/tp#96]
It seems that data is only saved upon using the exit command. Perhaps you could consider saving to the save file after any changes to the recipes, since if the program crashes for any reason, none of the changes that the user has made throughout the current session is saved.

![image.png](https://raw.githubusercontent.com/jeraldgau/ped/main/files/06482c86-5663-4802-b6d6-de091881cf82.png)

![image.png](https://raw.githubusercontent.com/jeraldgau/ped/main/files/2a1d571b-0db9-46ef-8dd9-10d9a143dfc6.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jeraldgau/ped#4

**Comment by jaredoong** [comment]
Will not implement this as of v2.1. However, a separate command to save the current data could be included in future iterations.
